[package]
name = "musicfree"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = [
  "json",
  "rustls-tls",
  "gzip",
], default-features = false }
tokio = { version = "1", features = ["full"] }
thiserror = "2"
regex = "1"
urlencoding = "2"
ejs = { version = "0.1", git = "https://github.com/ahaoboy/ytdlp-ejs", default-features = false, features = [
  "qjs",
] }
