[package]
name = "musicfree"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "musicfree"
repository = "https://github.com/ahaoboy/musicfree"
homepage = "https://github.com/ahaoboy/musicfree"
authors = ["ahaoboy"]

[features]
default = []
ytdlp-ejs = ["dep:ytdlp-ejs"]
bindgen = ["ytdlp-ejs", "ytdlp-ejs/bindgen"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = [
  "json",
  "rustls-tls",
  "gzip",
], default-features = false }
tokio = { version = "1", features = ["full"] }
thiserror = "2"
regex = "1"
urlencoding = "2"
ytdlp-ejs = { version = "0.1", git = "https://github.com/ahaoboy/ytdlp-ejs", default-features = false, optional = true, features = [
  "qjs",
] }
